---
- name: Deploy calculator app
  hosts: localhost
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: stsiyer/calculator-app  
        source: pull

    - name: Stop and remove existing container (if exists)
      docker_container:
        name: calculator-container
        state: absent
      ignore_errors: yes

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it --name calculator-container stsiyer/calculator-app
